version: '3.6'

services:
  zm-janus-db:
    container_name: zm-janus-db
    image: mariadb
    restart: unless-stopped
    networks:
      - traefik-ext
    volumes:
      - '/storage/zm-janus/db:/var/lib/mysql:z'
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - /storage/zm-janus/env

  zm-janus-gateway:
    container_name: zm-janus-gateway
    image: 'canyan/janus-gateway:master'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8888:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "20000-20050:20000-20050/udp"
    networks:
      - traefik-ext
    volumes:
      - "/storage/zm-janus/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "/storage/zm-janus/janus/janus.plugin.streaming.jcfg:/usr/local/etc/janus/janus.plugin.streaming.jcfg"
    restart: unless-stopped
    labels:
      # required when using --providers.docker.exposedbydefault=false
      - "traefik.enable=true"
      - "traefik.http.routers.zm-janus-gw.rule=Host(`janus-gorgon.example.com`)"
      - "traefik.http.routers.zm-janus-gw.entrypoints=web"
      - "traefik.http.services.zm-janu-gw.loadbalancer.server.port=8088"
      - "traefik.http.routers.zm-janus-gw.tls=true"
      - "traefik.docker.network=traefik-ext"
      - "traefik.http.routers.zm-janus-gw-secure.rule=Host(`janus-gorgon.example.com`)"
      - "traefik.http.routers.zm-janus-gw-secure.entrypoints=websecure"
      - "traefik.http.routers.zm-janus-gw-secure.tls=true"
      - "traefik.http.routers.zm-janus-gw-secure.tls.certresolver=le"

  zoneminder:
    container_name: zoneminder-janus
    # This image will run the latest nightly build of the ZM master branch.
    image: ghcr.io/zoneminder-containers/eventserver-base:nightly
    restart: unless-stopped
    stop_grace_period: 45s
    depends_on:
      - zm-janus-db
      - zm-janus-gateway
    ports:
      # - 80:80
      - "8081:80" #So I can access it on internal network on a shared host
      # - "443:443"
      - "2000:2000"
      - "9000:9000"
      - "6802:6802"
    networks:
      - traefik-ext
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - '/storage/zm-janus/data:/data:z'
      - '/storage/zm-janus/config:/config:z'
      - '/storage/zm-janus/log:/log:z'
      - '/storage/zm-janus/janus/janus.js:/var/www/html/javascript/janus/janus.js:z'
      - '/storage/docker/zm-janus/pushapi_pushover.py:/var/lib/zmeventnotification/bin/pushapi_pushover.py:z'
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2G
    env_file:
      - /storage/zm-janus/env
    labels:
      # required when using --providers.docker.exposedbydefault=false
      - "traefik.enable=true"
      - "traefik.http.routers.zm.rule=Host(`zm-janus.example.com`)"
      - "traefik.http.routers.zm.entrypoints=web"
      - "traefik.http.services.zm.loadbalancer.server.port=80"
      - "traefik.http.routers.zm.tls=true"
      - "traefik.docker.network=traefik-ext"
      - "traefik.http.routers.zm-secure.rule=Host(`zm-janus.example.com`)"
      - "traefik.http.routers.zm-secure.entrypoints=websecure"
      - "traefik.http.routers.zm-secure.tls=true"
      - "traefik.http.routers.zm-secure.tls.certresolver=le"

networks:
  traefik-ext:
    external: true
